name = "POMP"
uuid = "9bb39625-5a10-460f-ab4b-ef8792750c80"
authors = ["Aaron A. King"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
